Repository Baza-86/stale-securitygroup-rule-analysis-with-serverless-architecture, pull requests merged in 2023-08, with the labels that each got.

#12 Release 0.0.2
  .gitignore
  .gitmodules
  lambda_functions/GetENI/GetENITest-787e5a66-3dc8-4c70-b8a6-f9e4ba4761d5.zip
  lambda_functions/GetENI/lambda_function.py
  lambda_functions/GetSecurityGroups/GetSGTest-5635c8ba-9036-4b27-a232-ffb9f8874040.zip
  lambda_functions/GetSecurityGroups/lambda_function.py
  scripts/flow_logs_parser.py
  scripts/get_network_interfaces.py
  scripts/query_athena.py
  templates/s3_buckets.yaml
  templates/sg_rule_analysis.yaml
Labels: bug, enhancement

#27 Cross Account Role Template
  templates/cross_account_lambda_roles.yml
Labels: CloudFormation

#21 Add params to glue
  scripts/query_athena.py
  templates/sg_rule_analysis.yaml
Labels: enhancement

#30 SGA Lambda Functions Assume Cross Account Role
  templates/sg_rule_analysis.yaml
Labels: CloudFormation

#34 Release 0.0.3 Bugfix
  scripts/flow_logs_parser.py
  scripts/query_athena.py
  templates/sg_rule_analysis.yaml
Labels: bug

#26 Athena Integration
  data_structures/glue_table_columns.json
  templates/athena_integration_account_glue_table.yaml
  templates/athena_integration_database.yaml
Labels: enhancement, CloudFormation

#25 Template for VPC Flow Log Bucket
  templates/s3_flow_log_bucket.yaml
Labels: CloudFormation

#42 update step function and add data structure
  data_structures/state_machine_input.json
  templates/sg_rule_analysis.yaml
Labels: CloudFormation, Step Function

#40 38 refactor analysis with any any
  .gitignore
  scripts/flow_logs_parser.py
  scripts/query_athena.py
  templates/sg_rule_analysis.yaml
Labels: enhancement, Analysis Scripts

#46 Refactor Analysis Query Changes
  scripts/flow_logs_parser.py
  scripts/query_athena.py
  templates/sg_rule_analysis.yaml
Labels: enhancement, Analysis Scripts

#47 Scaling Solution
  templates/sg_rule_analysis.yaml
Labels: enhancement, CloudFormation

#48 EventBridge Rule
  templates/sg_rule_analysis.yaml
Labels: CloudFormation, Step Function

#51 Scaling for Dynamo DB Tables
  templates/sg_rule_analysis.yaml
Labels: bug, CloudFormation

#59 #58 update cross account roles template:
  templates/cross_account_lambda_roles.yml
Labels: CloudFormation
