Repository Baza-86/stale-securitygroup-rule-analysis-with-serverless-architecture, pull requests merged in 2023-07, with the labels that each got.

#1 Fixes
  scripts/create_dynamodb_tables.py
  scripts/flow_logs_parser.py
  scripts/get_security_groups_data.py
  scripts/query_athena.py
  scripts/sg_usage_analysis.py
  templates/sg_rule_analysis.yaml
Labels: bug

#5 Cloudformation improvements
  templates/sg_rule_analysis.yaml
Labels: enhancement

#2 Analysis Refactor
  .gitignore
  scripts/flow_logs_parser.py
  scripts/get_network_interfaces.py
  scripts/query_athena.py
Labels: bug, enhancement

#11 Lambda Function to Get Security Group Rules
  GetSGTest-5635c8ba-9036-4b27-a232-ffb9f8874040.zip
  lambda_function.py
  modules/aws_network/export.py
  modules/aws_network/securitygroup.py
  templates/sg_rule_analysis.yaml
Labels: enhancement

#15 Updated Permissions
  scripts/flow_logs_parser.py
  templates/sg_rule_analysis.yaml
Labels: enhancement

#18 Pre Release002 Bug fix and Changes
  templates/s3_buckets.yaml
  templates/sg_rule_analysis.yaml
Labels: bug, enhancement
